<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DELL" failures="1" tests="3" name="TS_012_CHANGE_PASSWORD.TC_005_CHANGE_PASSWORD_FUNCTIONALITY4" time="48.139" errors="0" timestamp="2024-05-07T14:46:48 IST" skipped="0">
  <testcase classname="TS_012_CHANGE_PASSWORD.TC_005_CHANGE_PASSWORD_FUNCTIONALITY4" name="navigate_to_change_password_page" time="18.272"/>
  <system-out>
    <![CDATA[method namenavigate_to_change_password_page
method status1]]>
  </system-out>
  <testcase classname="TS_012_CHANGE_PASSWORD.TC_005_CHANGE_PASSWORD_FUNCTIONALITY4" name="validate_password_field_red_mark" time="18.323">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at TS_012_CHANGE_PASSWORD.TC_005_CHANGE_PASSWORD_FUNCTIONALITY4.validate_password_field_red_mark(TC_005_CHANGE_PASSWORD_FUNCTIONALITY4.java:18)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validate_password_field_red_mark -->
  <system-out>
    <![CDATA[method namevalidate_password_field_red_mark]]>
  </system-out>
  <testcase classname="TS_012_CHANGE_PASSWORD.TC_005_CHANGE_PASSWORD_FUNCTIONALITY4" name="logging_valid_credentials_TC_LF_001" time="11.544"/>
  <system-out>
    <![CDATA[method namelogging_valid_credentials_TC_LF_001
method status1]]>
  </system-out>
</testsuite> <!-- TS_012_CHANGE_PASSWORD.TC_005_CHANGE_PASSWORD_FUNCTIONALITY4 -->
